version: '3.3'
services:
  app:
    build:
      context: ./
    restart: always
    environment:
      FACookieA: ${FACookieA}
      FACookieB: ${FACookieB}
      szuruUser: ${szuruUser}
      szuruToken: ${szuruToken}
    networks:
      - szurubooru_default

networks:
  szurubooru_default:
    external: true
