version: '3.3'
services:
  app:
    build:
      context: ./
    restart: always
    extra_hosts:
      - "imagearchive.flipped.codes:10.10.0.5"
    environment:
      FACookieA: ${FACookieA}
      FACookieB: ${FACookieB}
      szuruUser: ${szuruUser}
      szuruToken: ${szuruToken}
