name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: stardrive

    env:
      FACookieA: ${{ secrets.FACookieA }}
      FACookieB: ${{ secrets.FACookieB }}
      szuruUser: ${{ secrets.szuruUser }}
      szuruToken: ${{ secrets.szuruToken }}

    steps:
      - uses: actions/checkout@v2

      - name: Update 3rd party docker containers
        run: docker-compose pull

      - name: Build app
        run: docker-compose build

      - name: Spin up containers
        run: docker-compose up -d
