# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: raspiserver

    env:
      FACookieA: ${{ secrets.FACookieA }}
      FACookieB: ${{ secrets.FACookieB }}
      szuruToken: ${{ secrets.szuruToken }}

    steps:
      - uses: actions/checkout@v2

      - name: Update 3rd party docker containers
        run: docker-compose pull

      - name: Build app
        run: docker-compose build

      - name: Spin up containers
        run: docker-compose up -d
